#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          15
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# CUSTOM CONFIG
$HOME/.fehbg
$HOME/.config/polybar/launch.sh
systemctl --user start redshift
xfce4-power-manager
